### ISSUE TITLE
The return value of a function networkInterfaces and getNetworkInterfaces may  lead to errors

### ISSUE THREAD

**Issue by Fog3211** [FredKSchott/rollup-plugin-polyfill-node#35]
Some libraries (like [address](https://github.com/node-modules/address/blob/master/lib/address.js#L58))may use the return value of `os.networkInterfaces()`, if it is undefined, it may cause an error 

![image](https://user-images.githubusercontent.com/23151576/143220864-838f2ffb-e649-4c0f-bd69-8d7aecc11e62.png)
[https://github.com/calvinmetcalf/rollup-plugin-node-builtins/blob/master/src/es6/os.js#L81](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/blob/master/src/es6/os.js#L81)

Hope to be modified to be consistent with this。 [os-browserify](https://github.com/CoderPuppy/os-browserify/blob/master/browser.js#L35)

**Comment by Fog3211** [comment]
#36

**Comment by FredKSchott** [comment]
Fixed in #36
