### ISSUE TITLE
Update to rollup 4

### ISSUE THREAD

**Issue by Niek** [FredKSchott/rollup-plugin-polyfill-node#76]
The current release has peer dependency:
```
peer rollup@"^1.20.0 || ^2.0.0 || ^3.0.0"
```
Rollup 4 has been released: https://github.com/rollup/rollup/blob/master/CHANGELOG.md

It would be great if support could be added for rollup 4.

**Comment by Niek** [comment]
Open PR: https://github.com/FredKSchott/rollup-plugin-polyfill-node/pull/77

Ping @FredKSchott

**Comment by gregid** [comment]
Any news on the update?
